version: '3.8'
services:
  db:
    image: postgres:15
    container_name: devmatch-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devmatch
    ports:
      - '5432:5432'
    volumes:
      - devmatch-pg-data:/var/lib/postgresql/data

volumes:
  devmatch-pg-data:
